name: PPM Compile Advanced Configuration Manager v2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Add repoistory for PHP 8.0
        run: sudo add-apt-repository ppa:ondrej/php
      - name: Install PHP 8.0
        run: sudo apt-get install php8.0 php8.0-curl php8.0-mbstring php8.0-tokenizer php8.0-fileinfo

      - uses: actions/checkout@v2
        with:
          repository: intellivoid/ppm
          ref: "production"
          token: ${{ secrets.PPM_ACCESS_TOKEN }}
      - name: Install PPM
        run: sudo ./install
      - name: Configuring PPM
        run: sudo ppm --github-add-pat --alias="system" --token="${{ secrets.PPM_ACCESS_TOKEN }}"
      - uses: actions/checkout@master
      - name: Make build directory
        run: mkdir build

      - name: Prepare Advanced Configuration Manager v2
        run: ppm --generate-package="src/acm2"
      - name: Compile Advanced Configuration Manager v2
        run: ppm --no-intro --verbose --compile="src/acm2" --directory="build"
      - name: Install Advanced Configuration Manager v2
        run: sudo -H ppm --no-prompt --fix-conflict --verbose --install="build/net.intellivoid.acm2.ppm"